### PR TITLE
GH-500 Remove Changelog file.

### PR DESCRIPTION
**Pull request by vLuckyyy**
# READ BEFORE APPROVE 🔔🔔🔔

When I introduced this change, I thought it would be very useful. However, at the moment, I believe that releases should be issued at short intervals, which makes this file currently unnecessary. No one is adding information about their changes to this file; let's let GitHub manage the history of those changes. I will manage to detail the changes thoroughly during the release by utilizing commit names.

### CODE REVIEW

**Review by CitralFlo — APPROVED** [review]
Okej brzmi sensowie, zawsze możecie dropnąć opisy featurerów to uzupełnienie dokumentację.

**Review by Rollczi — CHANGES_REQUESTED** [review]
I think it is not a solution that will resolve our problems with documenting progress. During writing documentation you should have any context about problem/feature. Is waste of time for someone to perform that duty without context. Developer who create PR has more context than the others and  should write his/her changelog in one minute.

**Review by Jakubk15 — APPROVED** [review]
Good point, changelogs should be written along with a version release, and commit names should be meaningful, that is the way to go. We are also writing a brief release description on Discord, so this file is kinda useless.

**Comment by vLuckyyy** [comment]
> I think it is not a solution that will resolve our problems with documenting progress. During writing documentation you should have any context about problem/feature. Is waste of time for someone to perform that duty without context. Developer who create PR has more context than the others and should write his/her changelog in one minute.

THIS IS NOT DOCUMENTATION, this is a file.  which contains the name of the commit so that the person issuing the release can copy it to the changelog, currently meaningless, github can generate it, I am the one doing releases in the team, and I noticed that no one adds changes to this file, when doing releases I go to Issue/Pull  request, and I delve into what it's about and then I write a short note related to what has actually changed, for example, let's say I want to release release 1.0.1 eternal-core, the note would look like this:

https://github.com/EternalCodeTeam/EternalCore/assets/65517973/d1709204-62eb-48e1-b645-5f9bbbce48d3

**Comment by vLuckyyy** [comment]
> > I think it is not a solution that will resolve our problems with documenting progress. During writing documentation you should have any context about problem/feature. Is waste of time for someone to perform that duty without context. Developer who create PR has more context than the others and should write his/her changelog in one minute.
> 
> THIS IS NOT DOCUMENTATION, this is a file. which contains the name of the commit so that the person issuing the release can copy it to the changelog, currently meaningless, github can generate it, I am the one doing releases in the team, and I noticed that no one adds changes to this file, when doing releases I go to Issue/Pull request, and I delve into what it's about and then I write a short note related to what has actually changed, for example, let's say I want to release release 1.0.1 eternal-core, the note would look like this:
> 
>  2023-09-01.13-25-04.mov

After discussing with @Rollczi, I decided to close the pull request.

**Pull request closed without merging**
